### ISSUE TITLE
Why can't I open the exe file in Windows10?

### ISSUE THREAD

**Issue by Andrewyyc** [alphasoc/flightsim#51]
I downloaded flightsim in github release, and found that flightsim.exe is not available.

**Comment by mrozitron** [comment]
Hi @Andrewyyc,

I just had a look, and https://github.com/alphasoc/flightsim/releases/download/v2.2.1/flightsim_2.2.1_windows_amd64.tar.gz, when untar'd contains `flightsim.exe`.

Is this the file you downloaded?

**Comment by Andrewyyc** [comment]
Yes, exactly.

**Comment by mrozitron** [comment]
OK, so to make sure I understand the problem correctly, after untarring, `flightsim.exe` **is present**, but you're unable to execute it on Windows 10.  Correct?

**Comment by Andrewyyc** [comment]
Correct. My computer does not seem to respond to it.  The same problem also occurred in the previous version ( 2.2.0 ), so it might be a problem of my own computer. Do I need to download/install any other things in my system in order to execute it?

**Comment by mrozitron** [comment]
@Andrewyyc - I don't have a Windows 10 box in front of me at the moment to verify, but I'll get back to you later on today.

**Comment by Andrewyyc** [comment]
I gratefully appreciate for your help. ^_^

**Comment by mrozitron** [comment]
@Andrewyyc - managed to test on a latest windows server instance, and a colleague of mine on windows 10.  Is it a "Failed DNS probe" error that you were seeing?

**Comment by Andrewyyc** [comment]
I didn't see any notice of "Failed DNS probe". I clicked on "flightsim.exe" and then nothing happened.

**Comment by mrozitron** [comment]
@Andrewyyc: flightsim is a console application.  Once you untar the executable, you can run it from a command prompt/powershell.  From the powershell, execute it as: `.\flightsim.exe -h`  That will display a help message with further instructions on how to run some sample workloads.  Do have a look at the packaged README also.

For the interim, I've created a test-release on my fork for you to try.  Grab https://github.com/mrozitron/flightsim/releases/tag/test-win-fix and give it a run as mentioned above.  This test release will get you around the DNS probe issue we uncovered yesterday.  See if it works for you.  Once we push out a fix we'll publish 2.2.2 and I'll give you a heads up here so that you can grab the official release.

Have fun,
mrozitron

**Comment by Andrewyyc** [comment]
Great!  It works on my computer now. Thanks a lot!!!
