### ISSUE TITLE
Version number incorrect

### ISSUE THREAD

**Issue by misuchiru03** [alphasoc/flightsim#9]
More than just a PR, the `version/version.go` file shows `v0.0.0`.  See about changing this to match the version releases and have master show latest release.

**Comment by tg** [comment]
@misuchiru03 this is actually intended as we're replacing the `version.Version` variable during a build process by adding `-ldflags "-X github.com/alphasoc/flightsim/version.Version=$(git describe)`. IMO keeping code in sync with git tags is prone to mistakes.

Saying that, I think more readable solution would be to set the version variable to `"undefined"` and make an explicit comment in the code this is being replaced during the build.

**Comment by tg** [comment]
I made some version-related amendments in the latest release (https://github.com/alphasoc/flightsim/commit/bf2874f2a209e28edf3339b493483f5976bf366d). Instead of crafting own `version` command we just rely on cobra package, which support version printing. It means we have now `--version` flag instead of a separate command. 

Also, if version is not set during the build then it's empty string, which disables `--version` flag. I guess it makes more sense than printing `v0.0.0`.

There is a problem with builds via `go get` though as the version string is not being set then. I guess a Makefile would be required to solve it.
